[package]
name = "spliny"
version = "0.3.0"
edition = "2018"
description = "b-Spline Curves"
authors = ["Gerard Harbers", "Harbers Bik LLC"]
repository = "https://github.com/harbik/spliny"
keywords = ["basis-splines", "splines"]
license = "MIT OR Apache-2.0"


[dependencies]
plotters = {version = "0.3.7", optional = true }

[dev-dependencies]
approx = "0.5"

[features]
default = []
plot = ["dep:plotters"]

[[example]]
name = "cubic2d"
required-features = ["plot"]
